package utilitydy_10;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;

public class fileutility {

    //CREATE FILE
    public static boolean createfile(String fileNameWithPah) {
        File file = new File(fileNameWithPah);
        boolean fileCreated = false;

        try {

            fileCreated = file.createNewFile();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return fileCreated;
    }

    //READ FILE
    public static ArrayList<String> readFileAsList(String fileName) {
        Scanner scanner = null;
        ArrayList<String> strings = new ArrayList<String>();
        try {
            File file = new File(fileName);
            scanner = new Scanner(file);
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                strings.add(line);

            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (scanner != null) {
                scanner.close();
            }
        }
        return strings;

    }

    //WRITE FILE
    public static boolean writeToFile(String fileNameWithPath, String content) {
        try {
            FileWriter fileWriter = new FileWriter(fileNameWithPath);
            fileWriter.append(content);
            fileWriter.close();
        } catch (Exception e) {

        }
        return true;
    }

    //appending file
    public static boolean appendToFile(String fileName, String content) {
        try {
            FileWriter fileWriter = new FileWriter(fileName, true);
            fileWriter.append("\n");
            fileWriter.append(content);
            fileWriter.close();
        } catch (Exception e) {
            return false;
        }
        return true;
    }


    public static void main(String[] args) {
        System.out.println("This is Neha kumari");
        System.out.println("File Utility is running at " + new Date().toString() + " sharp.");
        String nameOfNewFile = "C:\\Users\\Lenovo\\IdeaProjects\\TechCodingMafia\\ data\\practice\\file" + "create-File.txt";
        boolean created = createfile(nameOfNewFile);
        System.out.println("File Created " + created);
        ArrayList<String> stringArrayList = readFileAsList(nameOfNewFile);
        for (String row : stringArrayList) {
            System.out.println("Line :" + row);
        }
        System.out.println("No. of Lines : " + stringArrayList.size());

        String nameOfWriteFile = "C:\\Users\\Lenovo\\IdeaProjects\\TechCodingMafia\\ data\\practice\\file" + "write-File.txt";
        boolean wroteToFile = writeToFile(nameOfWriteFile, "This file is generated by Adarsh");
        System.out.println(wroteToFile);

        for (int i = 1; i <= 100; i++) {
            String data = i + "";
            appendToFile(nameOfWriteFile, data);
        }
        System.out.println("Appended file length :" + readFileAsList(nameOfWriteFile).size());
    }


}